- name: Show React build contents
  hosts: web1
  become: yes
  vars:
    local_build_path: "{{ playbook_dir }}/build"

  tasks:
    - name: List files in build folder
      shell: ls -la "{{ local_build_path }}"
      register: build_files
      delegate_to: localhost

    - name: Show build folder contents
      debug:
        var: build_files.stdout_lines