- name: Deploy build
  hosts: web1
  become: yes
  vars:
    local_build_path: "{{ playbook_dir }}/build"
    local_temp_build_path: "/tmp/build.tar.gz"
    server_build_path: "/home/{{ ansible_user }}/valvet-demo"
    server_temp_archive: "{{ server_build_path }}/build.tar.gz"

  tasks:
    - name: Create archive from build
      community.general.archive:
        path: "{{ local_build_path }}"
        dest: "{{ local_temp_build_path }}"

    - name: Copy archive to server
      copy:
        src: "{{ local_temp_build_path }}"
        dest: "{{ server_temp_archive }}"

    - name: Extract archive on server
      unarchive:
        src: "{{ server_temp_archive }}"
        dest: "{{ server_build_path }}"
        remote_src: yes

    - name: Remove archive from runner
      shell: rm -f "{{ local_temp_build_path }}"
      delegate_to: localhost

    - name: Remove archive from server
      file:
        path: "{{ server_temp_archive }}"
        state: absent