- name: Deploy build
  hosts: web1
  become: yes
  vars:
    local_build_path: "{{ playbook_dir }}/build"
    local_temp_build_path: "/tmp/build.tar.gz"
    server_build_path: "/var/www/valvet-demo"
    server_temp_archive: "{{ server_build_path }}/build.tar.gz"
    domain_name: "valvet-demo.ashashkov.com"

  tasks:
    - name: Create archive from build contents on runner
      community.general.archive:
        path: "{{ local_build_path }}/*"
        dest: "{{ local_temp_build_path }}"
      delegate_to: localhost

    - name: Ensure server build path exists
      file:
        path: "{{ server_build_path }}"
        state: directory
        mode: "0755"

    - name: Copy archive to server
      copy:
        src: "{{ local_temp_build_path }}"
        dest: "{{ server_temp_archive }}"

    - name: Extract archive on server
      unarchive:
        src: "{{ server_temp_archive }}"
        dest: "{{ server_build_path }}"
        remote_src: yes

    - name: Remove archive from runner
      file:
        path: "{{ local_temp_build_path }}"
        state: absent
      delegate_to: localhost

    - name: Remove archive from server
      file:
        path: "{{ server_temp_archive }}"
        state: absent

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create Nginx config for site
      copy:
        dest: "/etc/nginx/sites-available/{{ domain_name }}"
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};

              root {{ server_build_path }};
              index index.html;

              location / {
                  try_files $uri /index.html;
              }
          }

    - name: Enable site by symlink
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link
        force: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
