- name: Deploy build
  hosts: web1
  become: yes
  vars:
    local_build_path: "{{ playbook_dir }}/build"
    server_build_path: "/home/{{ ansible_user }}/valvet-demo"
    nginx_root: /var/www/html

  tasks:
    - name: Ensure server build path exists
      file:
        path: "{{ server_build_path }}"
        state: directory

    - name: Copy build to the server
      copy:
        src: "{{ local_build_path }}/"
        dest: "{{ server_build_path }}/"