all:
  vars:
    ansible_user: deploy
    ansible_python_interpreter: /usr/bin/python3

  children:
    webservers:
      hosts:
        web1:
          ansible_host: "{{ lookup('env','SERVER_IP') }}"
          ansible_port: 22