- name: Configure Nginx
  hosts: web1
  become: yes
  vars:
    email: "{{ lookup('env','CERTBOT_EMAIL') }}"
    domain_name: "{{ lookup('env','DOMAIN_NAME') }}"
    server_build_path: "/var/www/{{ domain_name }}"
    nginx_sites_available: "/etc/nginx/sites-available"
    nginx_sites_enabled: "/etc/nginx/sites-enabled"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Check if Nginx config exists
      stat:
        path: "{{ nginx_sites_available }}/{{ domain_name }}"
      register: nginx_conf_stat

    - name: Create Nginx config
      copy:
        dest: "{{ nginx_sites_available }}/{{ domain_name }}"
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};

              root {{ server_build_path }};
              index index.html;

              location / {
                  try_files $uri /index.html;
              }
          }
      when: not nginx_conf_stat.stat.exists

    - name: Create symlink
      file:
        src: "{{ nginx_sites_available }}/{{ domain_name }}"
        dest: "{{ nginx_sites_enabled }}/{{ domain_name }}"
        state: link
        force: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Obtain SSL certificate via Certbot
      command: >
        certbot --nginx -n --agree-tos --redirect --email {{ email }} -d {{ domain_name }}
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
