- name: Configure Nginx
  hosts: web1
  become: yes
  vars:
    server_build_path: "/var/www/valvet-demo"
    email: "anton.shashkov.k@gmail.com"
    domain_name: "valvet-demo.ashashkov.com"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create Nginx config for site
      copy:
        dest: "/etc/nginx/sites-available/{{ domain_name }}"
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};

              root {{ server_build_path }};
              index index.html;

              location / {
                  try_files $uri /index.html;
              }
          }

    - name: Enable site by symlink
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link
        force: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Obtain SSL certificate via Certbot
      command: >
        certbot --nginx -n --agree-tos --redirect --email {{ email }} -d {{ domain_name }}
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
